[tool.poetry]
name = "advent-of-code-2024"
version = "1.0.0"
description = ""
authors = ["Marianna <joan.arvaniti@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
chardet = "5.2.0"
numpy = "*"
